comment:
  layout: "header, reach, files"
  require_changes: true
  behavior: "new" # Only post on new commits
coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 5%
