on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rust-version: 'stable-msvc'}
          - {os: windows-latest, r: 'devel',   rust-version: 'stable-msvc'}
          - {os: macOS-latest,   r: 'release', rust-version: 'stable'     }
          - {os: ubuntu-20.04,   r: 'release', rust-version: 'stable'     }
          - {os: ubuntu-20.04,   r: 'devel',   rust-version: 'stable'     }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.config.rust-version }}
          default: true

      - name: Configure Windows
        if: startsWith(runner.os, 'Windows') && matrix.config.r == 'release'
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add i686-pc-windows-gnu

      - name: Configure Windows (UCRT)
        if: startsWith(runner.os, 'Windows') && matrix.config.r == 'devel'
        run: |
          rustup target add x86_64-pc-windows-gnu
          echo "${env:RTOOLS40_HOME}\ucrt64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # To confirm the tests work without the legacy toolchains, remove them
          Remove-Item -Recurse -Force "${env:RTOOLS40_HOME}\mingw64"
          Remove-Item -Recurse -Force "${env:RTOOLS40_HOME}\mingw32"
        shell: pwsh

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1
