on:
  push:
    branches: [main, master, 'fix/R-4-3-release']
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }} - ${{ matrix.config.rust-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rust-version: 'stable-msvc', rust-target: 'x86_64-pc-windows-gnu' }
          - {os: windows-latest, r: 'devel',   rust-version: 'stable-msvc', rust-target: 'x86_64-pc-windows-gnu' }
          - {os: windows-latest, r: 'oldrel',  rust-version: 'stable-msvc', rust-target: 'x86_64-pc-windows-gnu' }

          - {os: macOS-latest,   r: 'release', rust-version: 'stable' }

          - {os: ubuntu-latest,  r: 'release', rust-version: 'stable' }
          - {os: ubuntu-latest,  r: 'devel',   rust-version: 'stable' }
          - {os: ubuntu-latest,  r: 'oldrel',  rust-version: 'stable' }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      REXTENDR_PATCH_CRATES_IO: 'libR-sys = { git = "https://github.com/extendr/libR-sys" }'

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.config.rust-version }}
          targets: ${{ join(',', matrix.config.rust-target) }}

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          # TODO: enable RSPM when all the packages are available
          use-public-rspm: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
